add_newline = true

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = " "

[git_status]
conflicted = "="
ahead = "󿙂 "
behind = "󿘿 "
diverged = "󿩎 "
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "󿘽 "
deleted = "󿙕 "

[rust]
symbol = " "

[docker_context]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "